services:
  app:
    build:
      context: .
    container_name: express-docker
    ports:
      - "${APP_PORT}:3000"
    volumes:
      - .:/usr/src/app            # Sinkronisasi source code
      - /usr/src/app/node_modules # Cegah node_modules host overwrite
    environment:
      NODE_ENV: "development"
      APP_NAME: ${APP_NAME}
      APP_ENV: "development"
      APP_DEBUG: "true"
    env_file:
    - .env
